# DEVINCEPT 

## SHIVANI PANKHANIA 
## ASSIGNMENT FOR MODULE 3
 
## NUMPY

In [6]:
import numpy as np 
a = np.array([1,2,3,4,5,6,7,8]) 
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
multi = np.array([[1, 2], [3, 4]]) 
multi

array([[1, 2],
       [3, 4]])

In [9]:
a.shape

(8,)

In [13]:
b = a.reshape(4,2)
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [16]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [17]:
a.dtype

dtype('int32')

In [18]:
arr = np.arange(3,7)
arr

array([3, 4, 5, 6])

In [19]:
arr[0]

3

In [20]:
arr[0:3]

array([3, 4, 5])

In [21]:
arr[-1]

6

In [23]:
arr.mean()

4.5

In [27]:
for i in arr:
    print(i)

3
4
5
6


In [29]:
for i in arr:
    if i%2==0:
        print(i, "even")
    else:
        print(i, "odd")

3 odd
4 even
5 odd
6 even
